/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ConexionMySQL;
import Controlador.ControladorLista;
import Controlador.ControladorUsuario;
import Modelo.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ControlDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ControlDeUsuario
     */
    boolean condi= true;
    ArrayList <Usuario> users;
    ConexionMySQL conexion;
    ControladorUsuario controladorUser;
    
    private static boolean isPasswordCorrect(char[] input, String contraseña) {
    boolean isCorrect = true;
    char[] correctPassword = contraseña.toCharArray();

    if (input.length != correctPassword.length) {
        isCorrect = false;
    } else {
        isCorrect = Arrays.equals (input, correctPassword);
    }

    //Zero out the password.
    Arrays.fill(correctPassword,'0');

    return isCorrect;
}
    public ControlDeUsuario() throws SQLException {
        initComponents();
        conexion = new ConexionMySQL("pasapalabra", "root", "");
        controladorUser = new ControladorUsuario (conexion);
        conexion.conectar();
        
        users = controladorUser.obtenerUsuario();
        
        System.out.println("Hola mundo");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConectar = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        psContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bConectar.setText("Conectarse");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });

        bRegistrarse.setText("Registrarse");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        tfNombre.setText("Usuario");
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        psContraseña.setText("Password");
        psContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bRegistrarse)
                            .addComponent(bConectar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre)
                            .addComponent(psContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(psContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(bConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bRegistrarse)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
        if (users.isEmpty()){
            JOptionPane.showMessageDialog(this, "No existe ningun usuario con ese nombre, intente registrandose", "ERROR!",
                    JOptionPane.WARNING_MESSAGE);
            
        }else{
            for (int i=0; i<users.size(); i++){
                if (users.get(i).getNombre().equalsIgnoreCase(tfNombre.getText())){
                    char [] input = psContraseña.getPassword();
                    if (isPasswordCorrect(input, users.get(i).getContraseña())){
                        JOptionPane.showMessageDialog(this, "Bienvenido " +  users.get(i).getNombre(), "Se ha conectado",
                                JOptionPane.INFORMATION_MESSAGE);
                        condi=false;
                        Menu menu = new Menu (users.get(i));
                        menu.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "ERROR!",
                                JOptionPane.WARNING_MESSAGE);
                        i=users.size();
                        
                    }
                }
            }
            if (condi){
            JOptionPane.showMessageDialog(this, "No existe ningun usuario con ese nombre, intente registrandose", "ERROR!",
                    JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bConectarActionPerformed

    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        char [] input = psContraseña.getPassword();
        if (tfNombre.getText().equalsIgnoreCase("Usuario")|| tfNombre.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Debe introducir un usuario", "ERROR!",
                    JOptionPane.WARNING_MESSAGE);
        }
        else{
            if (String.valueOf(input).equalsIgnoreCase("Password")||String.valueOf(input).equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this, "Debe introducir una contraseña util.", "ERROR!",
                    JOptionPane.WARNING_MESSAGE);
            }
        }
        if (!tfNombre.getText().equalsIgnoreCase("Usuario") && !tfNombre.getText().equalsIgnoreCase("")){
            if (!String.valueOf(input).equalsIgnoreCase("Password") && !String.valueOf(input).equalsIgnoreCase("")){
                
                condi= true;
                for (int i=0; i<users.size();i++){
                    if (users.get(i).getNombre().equalsIgnoreCase(tfNombre.getText()))
                        condi=false;
                }
                if (condi){
                    String consulta = "Insert into usuarios (nombre, contraseña, puntuacion) VALUES ('" + tfNombre.getText() + "', " + String.valueOf(psContraseña.getPassword()) + ", 0);";

                    try {
                        conexion.ejecutarInsetDeleteUpdate(consulta);
                        JOptionPane.showMessageDialog(this, "Se ha creado correctamente el usuario " + tfNombre.getText(), "Registrado",
                            JOptionPane.INFORMATION_MESSAGE);
                        users=controladorUser.obtenerUsuario();

                    } catch (SQLException ex) {
                        Logger.getLogger(ControlDeUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }
                else{
                    JOptionPane.showMessageDialog(this, "Ya existe ese usuario. Intente con otro nombre", "ERROR!",
                    JOptionPane.WARNING_MESSAGE);
                }
                
        

            }
        }
                
    }//GEN-LAST:event_bRegistrarseActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void psContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ControlDeUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ControlDeUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConectar;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
